version: '3'
services:
  redis:
    image: redis:5.0.0
    restart: "always"
    networks:
      - my_net
    container_name: redis
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /root/data/redis/data:/data
      - /root/data/redis/redis.conf:/etc/redis/redis.conf
  mysql:
    image: nacos/nacos-mysql:8.0.16
    restart: "always"
    networks:
      - my_net
    container_name: mysql_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nacos_config
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    ports:
      - '3306:3306'
    volumes:
      - /root/data/mysql/data/db:/var/lib/mysql"
      - /root/data/mysql/data/conf:/etc/mysql/conf.d"
  zookeeper:
    image: zookeeper
    restart: always
    networks:
      - my_net
    container_name: zookeeper
    privileged: true
    volumes:
      - /root/data/zk/config:/conf
      - /root/data/zk/data:/data
      - /root/data/zk/logs:/datalog
    ports: 
      - "2181:2181"
  nacos:
    image: nacos/nacos-server:2.0.0
    container_name: nacos
    hostname: nacos
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/nacos/logs/:/home/nacos/logs
      - /root/data/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9555:9555
    depends_on:
      - mysql
    restart: always
    networks:
      - my_net
  sentinel:
    image: bladex/sentinel-dashboard:1.8.0
    container_name: sentinel
    hostname: sentinel
    ports:
      - 8858:8858
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - my_net
  seata:
    image: seataio/seata-server:1.4.1
    container_name: seata
    hostname: server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - TZ=Asia/Shanghai
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/seata-server/resources/registry
    volumes:
      - /root/data/seata/config:/root/seata-config
      - /root/data/seata/resources/registry.conf:/seata-server/resources/registry.conf
    depends_on:
      - mysql
      - nacos
    restart: always
    networks:
      - my_net
networks:
  my_net:
    external:
      name: my_net